// connect_keystream_dump: runs the real transfer decryptor over zero-filled input and prints the
// AES-CTR keystream it produces, as a JSON array on stdout.
//
// The encrypted download (START_ENCRYPTED_DOWNLOAD) has the printer fetch a file over a plain HTTP
// connection of its own, decrypting with a key and IV the server chose. A server implementation has
// to produce the same keystream firmware will produce, and the part most likely to be wrong is not
// AES - it is how the starting offset seeds the counter: decrypt.cpp:23-28 overwrites the IV's last
// CtrCounterSize bytes with the block index, most significant first, and leaves the leading twelve
// alone. Encrypt a range at the wrong offset and the ciphertext looks fine and decrypts to garbage.
//
// Decrypting zeroes yields the raw keystream, because CTR XORs. That isolates exactly that question
// with no plaintext, no file and no HTTP in the way, and gives the other end a fixture it can check
// itself against byte for byte.
//
// The vectors below are chosen for the counter arithmetic rather than for AES: a block index that
// crosses each byte boundary, one taken from a transfer observed on real hardware, and one near the
// top of the uint32 file size firmware can express. Chunk sizes vary per vector so the decryptor's
// own partial-block state is exercised too - the output does not depend on them, which is the point.
//
// Not a test: it asserts nothing. It emits, and the assertions live on the server side.

#include <transfers/decrypt.hpp>

#include <algorithm>
#include <array>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <vector>

using std::vector;
using transfers::Decryptor;

namespace {

struct Vector {
    const char *name;
    Decryptor::Block key;
    Decryptor::Block iv;
    size_t offset;
    size_t length;
    /// How much is handed to decrypt() at a time. Must not change the output.
    size_t chunk;
};

/// The key and nonce from Prusa's own decrypt test (tests/unit/transfers/decrypt.cpp:41-42), which
/// decrypts a box.crypt/box.gcode pair produced by Connect itself. Reused here so one vector in this
/// file joins back to ciphertext that was not generated by either side of this exercise.
constexpr Decryptor::Block prusa_key = { 0x1c, 0x44, 0x5f, 0xac, 0x4b, 0xb4, 0x01, 0x7c, 0x1e, 0xff, 0x53, 0x73, 0xea, 0x7f, 0x95, 0x1d };
constexpr Decryptor::Block prusa_iv = { 0xa7, 0xf6, 0x5b, 0xce, 0xe0, 0xa6, 0xf4, 0x5f, 0xdf, 0x16, 0x9e, 0x31, 0x29, 0xf0, 0xa4, 0x37 };

/// Deliberately not random: a fixture regenerated at a newer firmware revision should differ only
/// where firmware changed. The trailing bytes are non-zero so that a counter seeded over the wrong
/// end of the IV cannot coincidentally agree.
constexpr Decryptor::Block ours_key = { 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff };
constexpr Decryptor::Block ours_iv = { 0xfe, 0xdc, 0xba, 0x98, 0x76, 0x54, 0x32, 0x10, 0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef };

const Vector vectors[] = {
    // The join to Prusa's own fixture pair. Block index 0, so the IV is the counter unchanged.
    { "prusa key, offset 0", prusa_key, prusa_iv, 0, 256, 16 },

    { "offset 0", ours_key, ours_iv, 0, 256, 1 },

    // Block index 1: the smallest offset that changes the counter at all.
    { "offset 16, block 1", ours_key, ours_iv, 16, 128, 13 },

    // Block index 256 - the first carry out of the low counter byte. A shift written the wrong way
    // round produces block 1 here and agrees with the vector above, so this is the one that catches
    // it.
    { "offset 4096, block 0x100", ours_key, ours_iv, 4096, 128, 37 },

    // Block index 65536: the second byte boundary.
    { "offset 1048576, block 0x10000", ours_key, ours_iv, 1048576, 128, 64 },

    // The tail start of the 1 914 803-byte transfer measured against the MK3.5 on 2026-07-28: the
    // printer asks for the tail of a large gcode first, so this is a real first-request offset
    // rather than a constructed one. Block index 0x1c740.
    { "offset 1864704, hardware tail start", ours_key, ours_iv, 1864704, 256, 256 },

    // Block index 0x0ffffffe, near the top of what a uint32 orig_size can address. All four counter
    // bytes significant, and one increment short of the low byte wrapping mid-stream.
    { "offset 4294967264, near the uint32 ceiling", ours_key, ours_iv, 4294967264u, 64, 17 },
};

void print_hex(const uint8_t *data, size_t length) {
    for (size_t i = 0; i < length; i++) {
        printf("%02hhx", data[i]);
    }
}

/// The keystream for one vector: CTR XORs, so decrypting zeroes returns it directly.
vector<uint8_t> keystream(const Vector &v) {
    Decryptor decryptor(v.key, v.iv, v.offset, v.length);

    const vector<uint8_t> zeroes(v.chunk, 0);
    vector<uint8_t> out;
    out.reserve(v.length);

    size_t produced = 0;

    while (produced < v.length) {
        const size_t want = std::min(v.chunk, v.length - produced);
        vector<uint8_t> buffer(want, 0);

        auto [in_used, out_used] = decryptor.decrypt(zeroes.data(), want, buffer.data(), want);
        (void)in_used;

        out.insert(out.end(), buffer.begin(), buffer.begin() + out_used);
        produced += out_used;
    }

    return out;
}

} // namespace

int main() {
    printf("[\n");

    bool first = true;

    for (const Vector &v : vectors) {
        if (!first) {
            printf(",\n");
        }

        first = false;

        const vector<uint8_t> stream = keystream(v);

        printf("  {\n");
        printf("    \"name\": \"%s\",\n", v.name);
        printf("    \"key\": \"");
        print_hex(v.key.data(), v.key.size());
        printf("\",\n");
        printf("    \"iv\": \"");
        print_hex(v.iv.data(), v.iv.size());
        printf("\",\n");
        printf("    \"offset\": %zu,\n", v.offset);
        printf("    \"chunk\": %zu,\n", v.chunk);
        printf("    \"keystream\": \"");
        print_hex(stream.data(), stream.size());
        printf("\"\n");
        printf("  }");
    }

    printf("\n]\n");

    return 0;
}
